DATA_CONNECTION_STR = 
GCS_PC_CONNECTION_STRS = []

AUTOMODE = False

PORT_I2C = 1
I2C_TIMEOUT = 1

LIS3MDL_ADRESS = 0x1e
LSM6DS3_ADRESS = 0x6B

ACCEL_SAMPLE_SIZE = 100
MAG_SAMPLE_SIZE = 100
GPS_SAMPLE_SIZE = 20

V_PUL_PIN = 18
V_DIR_PIN = 16
V_ENABLE_PIN = 32
V_GEARBOX_NUM = 102
V_DEG_PER_STEP = 1.8 / 8
V_P_LIMIT_PINS_MAP = {11:-9}
V_N_LIMIT_PINS_MAP = {7:-9}
V_STOP_STATE = 0

H_PUL_PIN = 13
H_DIR_PIN = 15
H_ENABLE_PIN = 31
H_GEARBOX_NUM = 102
H_DEG_PER_STEP = 1.8 / 8
H_P_LIMIT_PINS_MAP = {}
H_N_LIMIT_PINS_MAP = {}
H_STOP_STATE = 0

ANTENNA_AIMING_PERIOD = 0.5